// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBak_ingKLvQ5vykd4MdiryR3rVLwnvNSQ',
    appId: '1:387510940696:web:95d498c09c55f585f2ff6d',
    messagingSenderId: '387510940696',
    projectId: 'map-bloc-firebase-app',
    authDomain: 'map-bloc-firebase-app.firebaseapp.com',
    storageBucket: 'map-bloc-firebase-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8BDs3FQ-4w9Npc-bivFhQjc59NU-vcCI',
    appId: '1:387510940696:android:cc3990bf901c5311f2ff6d',
    messagingSenderId: '387510940696',
    projectId: 'map-bloc-firebase-app',
    storageBucket: 'map-bloc-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_qxoKmi6ns-nQxl4dRroWLMY9sx4tfA4',
    appId: '1:387510940696:ios:7045ff2b5b00d10ff2ff6d',
    messagingSenderId: '387510940696',
    projectId: 'map-bloc-firebase-app',
    storageBucket: 'map-bloc-firebase-app.appspot.com',
    iosClientId: '387510940696-ft0ob5m4hf6a5bkv4m51ds8prcokm937.apps.googleusercontent.com',
    iosBundleId: 'pl.com.appflow.mapBlocFirebaseApp',
  );
}
